/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Sign_upIndexRouteImport } from './routes/sign_up/index'
import { Route as Sign_inIndexRouteImport } from './routes/sign_in/index'
import { Route as ProductIndexRouteImport } from './routes/product/index'
import { Route as OrderIndexRouteImport } from './routes/order/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as Sign_upSplatRouteImport } from './routes/sign_up/$'
import { Route as Sign_inSplatRouteImport } from './routes/sign_in/$'
import { Route as ProductIdRouteImport } from './routes/product/$id'
import { Route as OrderIdRouteImport } from './routes/order/$id'
import { Route as CheckoutDoneRouteImport } from './routes/checkout/done'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Sign_upIndexRoute = Sign_upIndexRouteImport.update({
  id: '/sign_up/',
  path: '/sign_up/',
  getParentRoute: () => rootRouteImport,
} as any)
const Sign_inIndexRoute = Sign_inIndexRouteImport.update({
  id: '/sign_in/',
  path: '/sign_in/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const Sign_upSplatRoute = Sign_upSplatRouteImport.update({
  id: '/sign_up/$',
  path: '/sign_up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Sign_inSplatRoute = Sign_inSplatRouteImport.update({
  id: '/sign_in/$',
  path: '/sign_in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutDoneRoute = CheckoutDoneRouteImport.update({
  id: '/checkout/done',
  path: '/checkout/done',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout/done': typeof CheckoutDoneRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/sign_in/$': typeof Sign_inSplatRoute
  '/sign_up/$': typeof Sign_upSplatRoute
  '/admin': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/order': typeof OrderIndexRoute
  '/product': typeof ProductIndexRoute
  '/sign_in': typeof Sign_inIndexRoute
  '/sign_up': typeof Sign_upIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout/done': typeof CheckoutDoneRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/sign_in/$': typeof Sign_inSplatRoute
  '/sign_up/$': typeof Sign_upSplatRoute
  '/admin': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/order': typeof OrderIndexRoute
  '/product': typeof ProductIndexRoute
  '/sign_in': typeof Sign_inIndexRoute
  '/sign_up': typeof Sign_upIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout/done': typeof CheckoutDoneRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/sign_in/$': typeof Sign_inSplatRoute
  '/sign_up/$': typeof Sign_upSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/': typeof CartIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/order/': typeof OrderIndexRoute
  '/product/': typeof ProductIndexRoute
  '/sign_in/': typeof Sign_inIndexRoute
  '/sign_up/': typeof Sign_upIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout/done'
    | '/order/$id'
    | '/product/$id'
    | '/sign_in/$'
    | '/sign_up/$'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/order'
    | '/product'
    | '/sign_in'
    | '/sign_up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout/done'
    | '/order/$id'
    | '/product/$id'
    | '/sign_in/$'
    | '/sign_up/$'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/order'
    | '/product'
    | '/sign_in'
    | '/sign_up'
  id:
    | '__root__'
    | '/'
    | '/checkout/done'
    | '/order/$id'
    | '/product/$id'
    | '/sign_in/$'
    | '/sign_up/$'
    | '/admin/'
    | '/cart/'
    | '/checkout/'
    | '/order/'
    | '/product/'
    | '/sign_in/'
    | '/sign_up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutDoneRoute: typeof CheckoutDoneRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductIdRoute: typeof ProductIdRoute
  Sign_inSplatRoute: typeof Sign_inSplatRoute
  Sign_upSplatRoute: typeof Sign_upSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CartIndexRoute: typeof CartIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  OrderIndexRoute: typeof OrderIndexRoute
  ProductIndexRoute: typeof ProductIndexRoute
  Sign_inIndexRoute: typeof Sign_inIndexRoute
  Sign_upIndexRoute: typeof Sign_upIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign_up/': {
      id: '/sign_up/'
      path: '/sign_up'
      fullPath: '/sign_up'
      preLoaderRoute: typeof Sign_upIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign_in/': {
      id: '/sign_in/'
      path: '/sign_in'
      fullPath: '/sign_in'
      preLoaderRoute: typeof Sign_inIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign_up/$': {
      id: '/sign_up/$'
      path: '/sign_up/$'
      fullPath: '/sign_up/$'
      preLoaderRoute: typeof Sign_upSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign_in/$': {
      id: '/sign_in/$'
      path: '/sign_in/$'
      fullPath: '/sign_in/$'
      preLoaderRoute: typeof Sign_inSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/done': {
      id: '/checkout/done'
      path: '/checkout/done'
      fullPath: '/checkout/done'
      preLoaderRoute: typeof CheckoutDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutDoneRoute: CheckoutDoneRoute,
  OrderIdRoute: OrderIdRoute,
  ProductIdRoute: ProductIdRoute,
  Sign_inSplatRoute: Sign_inSplatRoute,
  Sign_upSplatRoute: Sign_upSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  CartIndexRoute: CartIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  OrderIndexRoute: OrderIndexRoute,
  ProductIndexRoute: ProductIndexRoute,
  Sign_inIndexRoute: Sign_inIndexRoute,
  Sign_upIndexRoute: Sign_upIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
